/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
WARNING 2025-08-17 15:13:31,257 middleware 46784 6165131264 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:13:31,259 middleware 46784 6165131264 Registro de auditoría creado: ACCESO por Usuario no identificado
Unauthorized: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:13:31] "GET /api/pacientes/cie10/buscar/?q=A00 HTTP/1.1" 401 65
WARNING 2025-08-17 15:13:40,044 middleware 46784 6165131264 No se pudo detectar usuario en middleware
[17/Aug/2025 15:13:40] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:13:40,056 middleware 46784 6165131264 No se pudo detectar usuario en middleware
[17/Aug/2025 15:13:40] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:13:42,415 middleware 46784 6165131264 No se pudo detectar usuario en middleware
[17/Aug/2025 15:13:42] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:13:42,753 middleware 46784 6165131264 No se pudo detectar usuario en middleware
[17/Aug/2025 15:13:42] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:13:47] "OPTIONS /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 200 0
WARNING 2025-08-17 15:13:47,040 middleware 46784 6165131264 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:13:47,056 middleware 46784 6165131264 Registro de auditoría creado: ACCESO por Usuario no identificado
Internal Server Error: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:13:47] "GET /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 500 173
INFO 2025-08-17 15:16:32,992 middleware 46784 6181957632 Usuario directo: jrochinu
INFO 2025-08-17 15:16:32,992 middleware 46784 6181957632 Usuario final en middleware: jrochinu
[17/Aug/2025 15:16:33] "GET /admin/patients/cie10mexico/?o=1.2 HTTP/1.1" 200 97315
INFO 2025-08-17 15:16:33,072 middleware 46784 6181957632 Usuario directo: jrochinu
INFO 2025-08-17 15:16:33,072 middleware 46784 6181957632 Usuario final en middleware: jrochinu
[17/Aug/2025 15:16:33] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
[17/Aug/2025 15:16:46] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
[17/Aug/2025 15:16:46] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:16:46,561 middleware 46784 6165131264 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:16:46,561 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:16:46] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:16:46] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:16:48] "OPTIONS /api/pacientes/buscar/?q=ecp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:16:48,920 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:16:48] "GET /api/pacientes/buscar/?q=ecp001 HTTP/1.1" 200 24
[17/Aug/2025 15:16:49] "OPTIONS /api/pacientes/buscar/?q=ecp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:16:49,209 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:16:49] "GET /api/pacientes/buscar/?q=ecp001 HTTP/1.1" 200 24
[17/Aug/2025 15:16:52] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:16:52,516 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:16:52] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:16:55] "OPTIONS /api/pacientes/buscar/?q=esp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:16:55,012 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:16:55] "GET /api/pacientes/buscar/?q=esp001 HTTP/1.1" 200 24
[17/Aug/2025 15:17:03] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:17:03,545 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:17:03] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:17:03] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:17:03,927 middleware 46784 6215610368 No se pudo detectar usuario en middleware
[17/Aug/2025 15:17:03] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:17:23] "OPTIONS /api/pacientes/cie10/buscar/?q=ex HTTP/1.1" 200 0
WARNING 2025-08-17 15:17:23,254 middleware 46784 6215610368 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:17:23,263 middleware 46784 6215610368 Registro de auditoría creado: ACCESO por Usuario no identificado
Internal Server Error: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:17:23] "GET /api/pacientes/cie10/buscar/?q=ex HTTP/1.1" 500 173
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:13:25
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Error en buscar_cie10: The field 'capitulo_info' was declared on serializer CIE10MexicoBusquedaSerializer, but has not been included in the 'fields' option.
Error en buscar_cie10: The field 'capitulo_info' was declared on serializer CIE10MexicoBusquedaSerializer, but has not been included in the 'fields' option.
/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:19:12
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
[17/Aug/2025 15:19:20] "OPTIONS /api/pacientes/cie10/buscar/?q=can HTTP/1.1" 200 0
WARNING 2025-08-17 15:19:20,285 middleware 47520 6191738880 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:19:20,300 middleware 47520 6191738880 Registro de auditoría creado: ACCESO por Usuario no identificado
Internal Server Error: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:19:20] "GET /api/pacientes/cie10/buscar/?q=can HTTP/1.1" 500 173
[17/Aug/2025 15:19:21] "OPTIONS /api/pacientes/cie10/buscar/?q=cancan HTTP/1.1" 200 0
WARNING 2025-08-17 15:19:21,867 middleware 47520 6191738880 No se pudo detectar usuario en middleware
[17/Aug/2025 15:19:21] "GET /api/pacientes/cie10/buscar/?q=cancan HTTP/1.1" 200 62
[17/Aug/2025 15:19:23] "OPTIONS /api/pacientes/cie10/buscar/?q=canca HTTP/1.1" 200 0
WARNING 2025-08-17 15:19:23,205 middleware 47520 6191738880 No se pudo detectar usuario en middleware
[17/Aug/2025 15:19:23] "GET /api/pacientes/cie10/buscar/?q=canca HTTP/1.1" 200 61
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:19:16
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Error en buscar_cie10: The field 'capitulo_info' was declared on serializer CIE10MexicoBusquedaSerializer, but has not been included in the 'fields' option.
/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
[17/Aug/2025 15:19:24] "OPTIONS /api/pacientes/cie10/buscar/?q=can HTTP/1.1" 200 0
WARNING 2025-08-17 15:19:24,567 middleware 47521 6200111104 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:19:24,579 middleware 47521 6200111104 Registro de auditoría creado: ACCESO por Usuario no identificado
Internal Server Error: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:19:24] "GET /api/pacientes/cie10/buscar/?q=can HTTP/1.1" 500 173
INFO 2025-08-17 15:20:12,820 middleware 47521 6216937472 Usuario directo: jrochinu
INFO 2025-08-17 15:20:12,820 middleware 47521 6216937472 Usuario final en middleware: jrochinu
[17/Aug/2025 15:20:12] "GET /admin/patients/cie10mexico/?o=1.2 HTTP/1.1" 200 97315
INFO 2025-08-17 15:20:12,902 middleware 47521 6216937472 Usuario directo: jrochinu
INFO 2025-08-17 15:20:12,902 middleware 47521 6216937472 Usuario final en middleware: jrochinu
[17/Aug/2025 15:20:12] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
INFO 2025-08-17 15:20:13,494 middleware 47521 6216937472 Usuario directo: jrochinu
INFO 2025-08-17 15:20:13,494 middleware 47521 6216937472 Usuario final en middleware: jrochinu
[17/Aug/2025 15:20:13] "GET /admin/patients/cie10mexico/?o=1.2 HTTP/1.1" 200 97315
INFO 2025-08-17 15:20:13,544 middleware 47521 6216937472 Usuario directo: jrochinu
INFO 2025-08-17 15:20:13,544 middleware 47521 6216937472 Usuario final en middleware: jrochinu
[17/Aug/2025 15:20:13] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
[17/Aug/2025 15:20:14] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:14,580 middleware 47521 6200111104 No se pudo detectar usuario en middleware
[17/Aug/2025 15:20:14] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:14,585 middleware 47521 6250590208 No se pudo detectar usuario en middleware
[17/Aug/2025 15:20:14] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:20:14] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:20:16] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:16,817 middleware 47521 6250590208 No se pudo detectar usuario en middleware
[17/Aug/2025 15:20:16] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:20:17] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:17,165 middleware 47521 6250590208 No se pudo detectar usuario en middleware
[17/Aug/2025 15:20:17] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:20:20] "OPTIONS /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:20,877 middleware 47521 6250590208 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:20:20,888 middleware 47521 6250590208 Registro de auditoría creado: ACCESO por Usuario no identificado
Internal Server Error: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:20:20] "GET /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 500 173
[17/Aug/2025 15:20:39] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
[17/Aug/2025 15:20:39] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:39,690 middleware 47521 6250590208 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:20:39,691 middleware 47521 6200111104 No se pudo detectar usuario en middleware
[17/Aug/2025 15:20:39] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:20:39] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:20:42] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:42,696 middleware 47521 6200111104 No se pudo detectar usuario en middleware
[17/Aug/2025 15:20:42] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:20:47] "OPTIONS /api/pacientes/cie10/buscar/?q=01 HTTP/1.1" 200 0
WARNING 2025-08-17 15:20:47,072 middleware 47521 6200111104 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:20:47,078 middleware 47521 6200111104 Registro de auditoría creado: ACCESO por Usuario no identificado
Internal Server Error: /api/pacientes/cie10/buscar/
[17/Aug/2025 15:20:47] "GET /api/pacientes/cie10/buscar/?q=01 HTTP/1.1" 500 173
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:19:24
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Error en buscar_cie10: The field 'capitulo_info' was declared on serializer CIE10MexicoBusquedaSerializer, but has not been included in the 'fields' option.
Error en buscar_cie10: The field 'capitulo_info' was declared on serializer CIE10MexicoBusquedaSerializer, but has not been included in the 'fields' option.
Error en buscar_cie10: The field 'capitulo_info' was declared on serializer CIE10MexicoBusquedaSerializer, but has not been included in the 'fields' option.
/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
[17/Aug/2025 15:22:31] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
[17/Aug/2025 15:22:31] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:31,730 middleware 47634 6152433664 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:22:31,730 middleware 47634 6135607296 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:31] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:22:31] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:22:35] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:35,134 middleware 47634 6152433664 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:35] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:35] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:35,472 middleware 47634 6152433664 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:35] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:38] "OPTIONS /api/pacientes/buscar/?q=expp00 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:39,000 middleware 47634 6152433664 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:39] "GET /api/pacientes/buscar/?q=expp00 HTTP/1.1" 200 24
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:22:22
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
[17/Aug/2025 15:22:39] "OPTIONS /api/pacientes/buscar/?q=ex HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:39,978 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:40] "GET /api/pacientes/buscar/?q=ex HTTP/1.1" 200 2473
[17/Aug/2025 15:22:41] "OPTIONS /api/pacientes/buscar/?q=exp01 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:41,085 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:41] "GET /api/pacientes/buscar/?q=exp01 HTTP/1.1" 200 2437
[17/Aug/2025 15:22:41] "OPTIONS /api/pacientes/buscar/?q=exp0 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:41,702 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:41] "GET /api/pacientes/buscar/?q=exp0 HTTP/1.1" 200 2454
[17/Aug/2025 15:22:42] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:42,437 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:42] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:44] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:44,342 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:44] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:44] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:44,800 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:44] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:45] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:45,017 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:45] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:45] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:45,185 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:45] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:45] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:45,331 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:45] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:45] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:45,486 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:45] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:45] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:45,621 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:45] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:22:51] "OPTIONS /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 200 0
WARNING 2025-08-17 15:22:51,174 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:22:51] "GET /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 200 3744
[17/Aug/2025 15:23:02] "OPTIONS /api/pacientes/cie10/buscar/?q=cap HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:02,047 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:02] "GET /api/pacientes/cie10/buscar/?q=cap HTTP/1.1" 200 4421
[17/Aug/2025 15:23:02] "OPTIONS /api/pacientes/cie10/buscar/?q=cap. HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:02,599 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:02] "GET /api/pacientes/cie10/buscar/?q=cap. HTTP/1.1" 200 60
[17/Aug/2025 15:23:03] "OPTIONS /api/pacientes/cie10/buscar/?q=cap. HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:03,568 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:03] "GET /api/pacientes/cie10/buscar/?q=cap. HTTP/1.1" 200 60
[17/Aug/2025 15:23:04] "OPTIONS /api/pacientes/cie10/buscar/?q=cap HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:04,322 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:04] "GET /api/pacientes/cie10/buscar/?q=cap HTTP/1.1" 200 4421
[17/Aug/2025 15:23:06] "OPTIONS /api/pacientes/cie10/buscar/?q=cancer HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:06,721 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:06] "GET /api/pacientes/cie10/buscar/?q=cancer HTTP/1.1" 200 62
[17/Aug/2025 15:23:09] "OPTIONS /api/pacientes/cie10/buscar/?q=c%C3%A1ncer HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:09,773 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:09] "GET /api/pacientes/cie10/buscar/?q=c%C3%A1ncer HTTP/1.1" 200 63
[17/Aug/2025 15:23:10] "OPTIONS /api/pacientes/cie10/buscar/?q=c%C3%A1nc HTTP/1.1" 200 0
WARNING 2025-08-17 15:23:10,814 middleware 47643 6199685120 No se pudo detectar usuario en middleware
[17/Aug/2025 15:23:10] "GET /api/pacientes/cie10/buscar/?q=c%C3%A1nc HTTP/1.1" 200 61
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:22:39
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

🔍 Iniciando búsqueda CIE-10 con query: ca
📝 Query: 'ca', Tipo: auto
✅ Encontrados 20 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cap
📝 Query: 'cap', Tipo: auto
✅ Encontrados 20 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cap.
📝 Query: 'cap.', Tipo: auto
✅ Encontrados 0 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cap.
📝 Query: 'cap.', Tipo: auto
✅ Encontrados 0 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cap
📝 Query: 'cap', Tipo: auto
✅ Encontrados 20 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cancer
📝 Query: 'cancer', Tipo: auto
✅ Encontrados 0 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cáncer
📝 Query: 'cáncer', Tipo: auto
✅ Encontrados 0 códigos
✅ Serialización exitosa
🔍 Iniciando búsqueda CIE-10 con query: cánc
📝 Query: 'cánc', Tipo: auto
✅ Encontrados 0 códigos
✅ Serialización exitosa
/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:25:01
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
[17/Aug/2025 15:25:10] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
[17/Aug/2025 15:25:10] "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:10,911 middleware 47929 6145323008 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:25:10,911 middleware 47929 6128496640 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:10] "GET /api/auth/profile/ HTTP/1.1" 200 298
[17/Aug/2025 15:25:10] "GET /api/auth/profile/ HTTP/1.1" 200 298
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:25:03
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:25:12
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
[17/Aug/2025 15:25:21] "OPTIONS /api/pacientes/buscar/?q=exp011 HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:21,121 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:21] "GET /api/pacientes/buscar/?q=exp011 HTTP/1.1" 200 280
[17/Aug/2025 15:25:23] "OPTIONS /api/pacientes/buscar/?q=exp0 HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:23,002 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:23] "GET /api/pacientes/buscar/?q=exp0 HTTP/1.1" 200 2454
[17/Aug/2025 15:25:24] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:24,170 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:24] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
[17/Aug/2025 15:25:29] "OPTIONS /api/pacientes/EXP001/historial/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:29,290 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:29] "GET /api/pacientes/EXP001/historial/ HTTP/1.1" 200 3936
[17/Aug/2025 15:25:49] "OPTIONS /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:49,408 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:49] "GET /api/pacientes/cie10/buscar/?q=ca HTTP/1.1" 200 2142
[17/Aug/2025 15:25:51] "OPTIONS /api/pacientes/cie10/buscar/?q=can HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:51,660 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:51] "GET /api/pacientes/cie10/buscar/?q=can HTTP/1.1" 200 1839
[17/Aug/2025 15:25:52] "OPTIONS /api/pacientes/cie10/buscar/?q=cancer HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:52,859 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:52] "GET /api/pacientes/cie10/buscar/?q=cancer HTTP/1.1" 200 71
[17/Aug/2025 15:25:55] "OPTIONS /api/pacientes/cie10/buscar/?q=c%C3%A1n HTTP/1.1" 200 0
WARNING 2025-08-17 15:25:55,124 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:25:55] "GET /api/pacientes/cie10/buscar/?q=c%C3%A1n HTTP/1.1" 200 69
[17/Aug/2025 15:26:09] "OPTIONS /api/pacientes/cie10/buscar/?q=tuer HTTP/1.1" 200 0
WARNING 2025-08-17 15:26:09,814 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:26:09] "GET /api/pacientes/cie10/buscar/?q=tuer HTTP/1.1" 200 69
[17/Aug/2025 15:26:10] "OPTIONS /api/pacientes/cie10/buscar/?q=tu HTTP/1.1" 200 0
WARNING 2025-08-17 15:26:10,420 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:26:10] "GET /api/pacientes/cie10/buscar/?q=tu HTTP/1.1" 200 2282
[17/Aug/2025 15:26:11] "OPTIONS /api/pacientes/cie10/buscar/?q=tuber HTTP/1.1" 200 0
WARNING 2025-08-17 15:26:11,061 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:26:11] "GET /api/pacientes/cie10/buscar/?q=tuber HTTP/1.1" 200 2398
INFO 2025-08-17 15:27:42,770 middleware 47954 6221213696 Usuario directo: jrochinu
INFO 2025-08-17 15:27:42,770 middleware 47954 6221213696 Usuario final en middleware: jrochinu
[17/Aug/2025 15:27:42] "GET /admin/patients/cie10mexico/?o=1.2&prinmorta=041 HTTP/1.1" 200 40560
INFO 2025-08-17 15:27:42,841 middleware 47954 6221213696 Usuario directo: jrochinu
INFO 2025-08-17 15:27:42,841 middleware 47954 6221213696 Usuario final en middleware: jrochinu
[17/Aug/2025 15:27:42] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
[17/Aug/2025 15:27:51] "OPTIONS /api/pacientes/cie10/buscar/?q=traco HTTP/1.1" 200 0
WARNING 2025-08-17 15:27:51,138 middleware 47954 6204387328 No se pudo detectar usuario en middleware
[17/Aug/2025 15:27:51] "GET /api/pacientes/cie10/buscar/?q=traco HTTP/1.1" 200 975
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:25:16
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:28:49
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
WARNING 2025-08-17 15:29:29,730 middleware 48353 6160248832 No se pudo detectar usuario en middleware
[17/Aug/2025 15:29:29] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:29:29,737 middleware 48353 6160248832 No se pudo detectar usuario en middleware
[17/Aug/2025 15:29:29] "GET /api/auth/profile/ HTTP/1.1" 200 298
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:29:00
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
WARNING 2025-08-17 15:29:35,167 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:29:35] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:29:35,525 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:29:35] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:29:40,706 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:29:40] "GET /api/pacientes/cie10/buscar/?q=traco HTTP/1.1" 200 2339
INFO 2025-08-17 15:30:34,731 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:30:34,731 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:30:34] "GET /admin/patients/cie10mexico/A71/change/?_changelist_filters=o%3D1.2%26prinmorta%3D041 HTTP/1.1" 200 37197
INFO 2025-08-17 15:30:34,781 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:30:34,781 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:30:34] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
[17/Aug/2025 15:31:47] "OPTIONS /api/pacientes/cie10/buscar/?q=A710 HTTP/1.1" 200 0
WARNING 2025-08-17 15:31:47,586 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:31:47] "GET /api/pacientes/cie10/buscar/?q=A710 HTTP/1.1" 200 502
WARNING 2025-08-17 15:31:56,355 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:31:56] "GET /api/pacientes/cie10/buscar/?q=A710 HTTP/1.1" 200 502
WARNING 2025-08-17 15:32:14,208 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:14] "GET /api/pacientes/cie10/buscar/?q=A710 HTTP/1.1" 200 502
[17/Aug/2025 15:32:21] "OPTIONS /api/pacientes/cie10/buscar/?q=gr HTTP/1.1" 200 0
WARNING 2025-08-17 15:32:21,107 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:21] "GET /api/pacientes/cie10/buscar/?q=gr HTTP/1.1" 200 4110
WARNING 2025-08-17 15:32:22,156 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:22] "GET /api/pacientes/cie10/buscar/?q=traco HTTP/1.1" 200 2339
[17/Aug/2025 15:32:42] "OPTIONS /api/pacientes/EXP001/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:32:42,719 middleware 48603 6198784000 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:32:42,724 middleware 48603 6198784000 Registro de auditoría creado: ACCESO por Usuario no identificado
[17/Aug/2025 15:32:42] "PATCH /api/pacientes/EXP001/ HTTP/1.1" 200 276
WARNING 2025-08-17 15:32:45,495 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:45] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:32:45,498 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:45] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:32:50,189 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:50] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:32:50,536 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:32:50] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:33:43,026 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:33:43] "GET /api/pacientes/cie10/buscar/?q=traco HTTP/1.1" 200 2339
[17/Aug/2025 15:34:31] "OPTIONS /api/recetas/estadisticas/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:34:31,966 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:34:31] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
[17/Aug/2025 15:34:31] "OPTIONS /api/reports/dashboard/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:34:31,973 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:34:31] "GET /api/reports/dashboard/ HTTP/1.1" 200 516
[17/Aug/2025 15:34:33] "OPTIONS /api/audit/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:34:33,682 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:34:33] "OPTIONS /api/audit/stats/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:34:33,683 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:34:33] "GET /api/audit/ HTTP/1.1" 200 6417
[17/Aug/2025 15:34:33] "GET /api/audit/stats/ HTTP/1.1" 200 918
WARNING 2025-08-17 15:34:59,832 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:34:59] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:34:59,842 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:34:59] "GET /api/reports/dashboard/ HTTP/1.1" 200 516
[17/Aug/2025 15:35:04] "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
INFO 2025-08-17 15:35:04,785 middleware 48603 6232436736 Usuario detectado en login: jrochinu
INFO 2025-08-17 15:35:04,785 middleware 48603 6232436736 Usuario final en middleware: jrochinu
INFO 2025-08-17 15:35:04,852 middleware 48603 6232436736 Registro de auditoría creado: LOGIN por jrochinu
[17/Aug/2025 15:35:04] "POST /api/auth/login/ HTTP/1.1" 200 803
WARNING 2025-08-17 15:35:04,869 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:35:04] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:35:04,873 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:35:04] "GET /api/reports/dashboard/ HTTP/1.1" 200 516
WARNING 2025-08-17 15:35:06,194 middleware 48603 6232436736 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:35:06,195 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:35:06] "GET /api/audit/ HTTP/1.1" 200 6421
[17/Aug/2025 15:35:06] "GET /api/audit/stats/ HTTP/1.1" 200 919
WARNING 2025-08-17 15:35:12,348 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:35:12] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:35:12,354 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:35:12] "GET /api/reports/dashboard/ HTTP/1.1" 200 516
INFO 2025-08-17 15:35:18,832 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:18,832 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:18] "GET /admin/patients/cie10mexico/A71/history/?_changelist_filters=o%3D1.2%26prinmorta%3D041 HTTP/1.1" 200 11077
INFO 2025-08-17 15:35:21,889 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:21,889 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:21] "GET /admin/audit/systemmovement/ HTTP/1.1" 200 36073
INFO 2025-08-17 15:35:21,920 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:21,920 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:21] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
INFO 2025-08-17 15:35:41,198 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:41,198 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:41] "GET /admin/audit/systemmovement/?is_successful__exact=1 HTTP/1.1" 200 24008
INFO 2025-08-17 15:35:41,219 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:41,219 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:41] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
INFO 2025-08-17 15:35:42,567 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:42,567 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:42] "GET /admin/audit/systemmovement/?is_successful__exact=0 HTTP/1.1" 200 32723
INFO 2025-08-17 15:35:42,590 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:42,590 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:42] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
INFO 2025-08-17 15:35:53,964 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:53,964 middleware 48603 6215610368 Usuario final en middleware: jrochinu
INFO 2025-08-17 15:35:53,978 middleware 48603 6215610368 Registro de auditoría creado: CREAR por jrochinu
[17/Aug/2025 15:35:53] "POST /admin/audit/systemmovement/?is_successful__exact=0 HTTP/1.1" 200 18116
INFO 2025-08-17 15:35:54,964 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:54,964 middleware 48603 6215610368 Usuario final en middleware: jrochinu
INFO 2025-08-17 15:35:54,987 middleware 48603 6215610368 Registro de auditoría creado: CREAR por jrochinu
[17/Aug/2025 15:35:54] "POST /admin/audit/systemmovement/?is_successful__exact=0 HTTP/1.1" 302 0
INFO 2025-08-17 15:35:54,993 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:54,993 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:54] "GET /admin/audit/systemmovement/?is_successful__exact=0 HTTP/1.1" 200 17306
INFO 2025-08-17 15:35:55,009 middleware 48603 6215610368 Usuario directo: jrochinu
INFO 2025-08-17 15:35:55,009 middleware 48603 6215610368 Usuario final en middleware: jrochinu
[17/Aug/2025 15:35:55] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
WARNING 2025-08-17 15:35:58,734 middleware 48603 6198784000 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:35:58,734 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:35:58] "GET /api/audit/ HTTP/1.1" 200 4046
[17/Aug/2025 15:35:58] "GET /api/audit/stats/ HTTP/1.1" 200 883
WARNING 2025-08-17 15:36:09,520 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:09] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:36:09,523 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:09] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:36:09,536 middleware 48603 6232436736 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:36:09,536 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:09] "GET /api/audit/ HTTP/1.1" 200 4046
[17/Aug/2025 15:36:09] "GET /api/audit/stats/ HTTP/1.1" 200 883
WARNING 2025-08-17 15:36:17,906 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:17] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:36:17,912 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:17] "GET /api/reports/dashboard/ HTTP/1.1" 200 516
[17/Aug/2025 15:36:42] "OPTIONS /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 0
WARNING 2025-08-17 15:36:42,356 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:42] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11911
[17/Aug/2025 15:36:52] "OPTIONS /api/recetas/91/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:36:52,489 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:52] "GET /api/recetas/91/ HTTP/1.1" 200 1560
[17/Aug/2025 15:36:58] "OPTIONS /api/recetas/91/actualizar-estado/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:36:58,067 middleware 48603 6198784000 No se pudo detectar usuario en middleware
Error al auditar cambios de PRESCRIPTION: 'Receta' object has no attribute 'id'
INFO 2025-08-17 15:36:58,074 middleware 48603 6198784000 Registro de auditoría creado: CREAR por Usuario no identificado
[17/Aug/2025 15:36:58] "POST /api/recetas/91/actualizar-estado/ HTTP/1.1" 200 1642
WARNING 2025-08-17 15:36:59,629 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:59] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:36:59,635 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:36:59] "GET /api/reports/dashboard/ HTTP/1.1" 200 516
WARNING 2025-08-17 15:37:01,308 middleware 48603 6232436736 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:01] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:01,309 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:01] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
[17/Aug/2025 15:37:01] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&sort_by=prioridad HTTP/1.1" 200 15746
[17/Aug/2025 15:37:02] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=e&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:02,519 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:02] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=e&sort_by=prioridad HTTP/1.1" 200 15746
[17/Aug/2025 15:37:02] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=ex&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:02,723 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:02] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=ex&sort_by=prioridad HTTP/1.1" 200 15746
[17/Aug/2025 15:37:02] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:02,779 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:02] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp&sort_by=prioridad HTTP/1.1" 200 15746
[17/Aug/2025 15:37:02] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp0&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:02,977 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:03] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp0&sort_by=prioridad HTTP/1.1" 200 14704
[17/Aug/2025 15:37:03] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp08&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:03,899 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:03] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp08&sort_by=prioridad HTTP/1.1" 200 1617
[17/Aug/2025 15:37:03] "OPTIONS /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:03,947 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:03] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 569
WARNING 2025-08-17 15:37:09,125 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:09] "GET /api/recetas/91/ HTTP/1.1" 200 1642
WARNING 2025-08-17 15:37:12,355 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:12] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
WARNING 2025-08-17 15:37:13,921 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:13] "GET /api/recetas/91/ HTTP/1.1" 200 1642
[17/Aug/2025 15:37:33] "OPTIONS /api/recetas/detalles/273/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:33,316 middleware 48603 6198784000 No se pudo detectar usuario en middleware
Error al auditar cambios de PRESCRIPTION: 'Receta' object has no attribute 'id'
INFO 2025-08-17 15:37:33,325 middleware 48603 6198784000 Registro de auditoría creado: ACCESO por Usuario no identificado
[17/Aug/2025 15:37:33] "PATCH /api/recetas/detalles/273/ HTTP/1.1" 200 516
WARNING 2025-08-17 15:37:33,330 middleware 48603 6198784000 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:33] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:29:32
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
WARNING 2025-08-17 15:37:35,617 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:35] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:37:35,630 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:35] "GET /api/reports/dashboard/ HTTP/1.1" 200 515
[17/Aug/2025 15:37:41] "OPTIONS /api/recetas/completadas/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:41,268 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:41] "GET /api/recetas/completadas/ HTTP/1.1" 200 13178
WARNING 2025-08-17 15:37:42,354 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:42] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
[17/Aug/2025 15:37:43] "OPTIONS /api/recetas/completadas/?expediente=e HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:43,350 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:43] "GET /api/recetas/completadas/?expediente=e HTTP/1.1" 200 13178
[17/Aug/2025 15:37:43] "OPTIONS /api/recetas/completadas/?expediente=ex HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:43,519 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:43] "GET /api/recetas/completadas/?expediente=ex HTTP/1.1" 200 13178
[17/Aug/2025 15:37:43] "OPTIONS /api/recetas/completadas/?expediente=exp HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:43,604 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:43] "GET /api/recetas/completadas/?expediente=exp HTTP/1.1" 200 13178
[17/Aug/2025 15:37:43] "OPTIONS /api/recetas/completadas/?expediente=exp0 HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:43,851 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:43] "GET /api/recetas/completadas/?expediente=exp0 HTTP/1.1" 200 12660
[17/Aug/2025 15:37:44] "OPTIONS /api/recetas/completadas/?expediente=exp08 HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:44,137 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:44] "GET /api/recetas/completadas/?expediente=exp08 HTTP/1.1" 200 2163
[17/Aug/2025 15:37:44] "OPTIONS /api/recetas/completadas/?expediente=exp089 HTTP/1.1" 200 0
WARNING 2025-08-17 15:37:44,202 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:44] "GET /api/recetas/completadas/?expediente=exp089 HTTP/1.1" 200 588
WARNING 2025-08-17 15:37:45,238 middleware 48872 6128873472 No se pudo detectar usuario en middleware
[17/Aug/2025 15:37:45] "GET /api/recetas/91/ HTTP/1.1" 200 1698
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:37:35
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
WARNING 2025-08-17 15:38:01,308 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:01] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 24
WARNING 2025-08-17 15:38:05,514 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:05] "GET /api/recetas/91/ HTTP/1.1" 200 1698
WARNING 2025-08-17 15:38:07,237 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:07] "GET /api/recetas/91/ HTTP/1.1" 200 1698
WARNING 2025-08-17 15:38:09,611 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:09] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:38:12,356 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:12] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
[17/Aug/2025 15:38:23] "OPTIONS /api/inventory/medicamentos/?search=&categoria=&stock_filter= HTTP/1.1" 200 0
WARNING 2025-08-17 15:38:23,785 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:24] "GET /api/inventory/medicamentos/?search=&categoria=&stock_filter= HTTP/1.1" 200 1465199
WARNING 2025-08-17 15:38:37,570 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:38] "GET /api/inventory/medicamentos/?search=&categoria=&stock_filter= HTTP/1.1" 200 1465199
WARNING 2025-08-17 15:38:39,568 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:39] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:38:42,352 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:38:42] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
WARNING 2025-08-17 15:39:01,309 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:39:01] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 24
WARNING 2025-08-17 15:39:11,548 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:39:11] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:39:12,354 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:39:12] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
[17/Aug/2025 15:39:17] "OPTIONS /api/pacientes/cie10/buscar/?q=te HTTP/1.1" 200 0
WARNING 2025-08-17 15:39:17,962 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:39:17] "GET /api/pacientes/cie10/buscar/?q=te HTTP/1.1" 200 4296
INFO 2025-08-17 15:39:31,142 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:39:31,142 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:39:31] "GET /admin/patients/cie10mexico/ HTTP/1.1" 200 90940
INFO 2025-08-17 15:39:31,212 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:39:31,212 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:39:31] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
INFO 2025-08-17 15:39:34,802 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:39:34,802 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:39:34] "GET /admin/patients/cie10mexico/?p=4 HTTP/1.1" 200 93139
INFO 2025-08-17 15:39:34,864 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:39:34,864 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:39:34] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
[17/Aug/2025 15:39:41] "OPTIONS /api/pacientes/cie10/buscar/?q=rabia HTTP/1.1" 200 0
WARNING 2025-08-17 15:39:41,218 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:39:41] "GET /api/pacientes/cie10/buscar/?q=rabia HTTP/1.1" 200 2373
WARNING 2025-08-17 15:39:42,353 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:39:42] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
WARNING 2025-08-17 15:40:01,308 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:40:01] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 24
INFO 2025-08-17 15:40:09,678 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:40:09,678 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:40:09] "GET /admin/patients/paciente/ HTTP/1.1" 200 81984
INFO 2025-08-17 15:40:09,763 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:40:09,763 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:40:09] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
WARNING 2025-08-17 15:40:12,932 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:40:12] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
INFO 2025-08-17 15:40:13,080 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:40:13,080 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:40:13] "GET /admin/patients/paciente/?q=exp001 HTTP/1.1" 200 19850
INFO 2025-08-17 15:40:13,197 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:40:13,197 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:40:13] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
INFO 2025-08-17 15:40:15,366 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:40:15,366 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:40:15] "GET /admin/patients/paciente/EXP001/change/?_changelist_filters=q%3Dexp001 HTTP/1.1" 200 29166
INFO 2025-08-17 15:40:15,395 middleware 49108 6178418688 Usuario directo: jrochinu
INFO 2025-08-17 15:40:15,395 middleware 49108 6178418688 Usuario final en middleware: jrochinu
[17/Aug/2025 15:40:15] "GET /admin/jsi18n/ HTTP/1.1" 200 8570
WARNING 2025-08-17 15:40:42,933 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:40:42] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
WARNING 2025-08-17 15:41:01,933 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:41:01] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 24
WARNING 2025-08-17 15:41:12,933 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:41:12] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
WARNING 2025-08-17 15:42:01,939 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:42:01] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&search=exp089&sort_by=prioridad HTTP/1.1" 200 24
WARNING 2025-08-17 15:42:23,126 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:42:23] "GET /api/recetas/cola-validacion/?estado=PENDIENTE HTTP/1.1" 200 11364
WARNING 2025-08-17 15:42:35,680 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:42:35] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:42:35,683 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:42:35] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:42:37,534 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:42:37] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:42:37,886 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:42:37] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:43:59,973 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:43:59] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:43:59,976 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:43:59] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:00,527 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:00] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:00,531 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:00] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:00,698 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:00] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:00,700 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:00] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:01,000 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:01] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:01,003 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:01] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:01,273 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:01] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:01,276 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:01] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:44:03,215 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:44:03] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:45:09,330 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:09] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:45:09,338 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:09] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:45:12,524 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:12] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 274
WARNING 2025-08-17 15:45:14,099 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:14] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 640
[17/Aug/2025 15:45:14] "OPTIONS /api/pacientes/cie10/buscar/?q=I10 HTTP/1.1" 200 0
WARNING 2025-08-17 15:45:14,116 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:14] "GET /api/pacientes/cie10/buscar/?q=I10 HTTP/1.1" 200 518
WARNING 2025-08-17 15:45:20,217 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:20] "GET /api/pacientes/cie10/buscar/?q=rabia HTTP/1.1" 200 2373
WARNING 2025-08-17 15:45:23,377 middleware 49108 6161592320 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:45:23,382 middleware 49108 6161592320 Registro de auditoría creado: ACCESO por Usuario no identificado
[17/Aug/2025 15:45:23] "PATCH /api/pacientes/EXP001/ HTTP/1.1" 200 388
WARNING 2025-08-17 15:45:47,026 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:47] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:45:47,032 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:47] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:45:50,601 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:50] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:45:51,008 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:45:51] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:46:04,844 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:04] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
[17/Aug/2025 15:46:04] "OPTIONS /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 0
WARNING 2025-08-17 15:46:04,852 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:04] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:46:09,122 middleware 49108 6161592320 No se pudo detectar usuario en middleware
INFO 2025-08-17 15:46:09,128 middleware 49108 6161592320 Registro de auditoría creado: ACCESO por Usuario no identificado
[17/Aug/2025 15:46:09] "PATCH /api/pacientes/EXP001/ HTTP/1.1" 200 388
WARNING 2025-08-17 15:46:12,001 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:12] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:46:12,003 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:12] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:46:14,287 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:14] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:46:14,702 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:14] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:46:21,166 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:21] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:46:21,178 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:46:21] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:47:22,877 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:22] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:47:22,888 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:22] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:47:32,305 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:32] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:47:32,313 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:32] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:47:37,398 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:37] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:47:37,404 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:37] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:47:55,751 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:55] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:47:56,088 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:47:56] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:48:01,873 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:48:01] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:48:01,877 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:48:01] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
[17/Aug/2025 15:48:32] "OPTIONS /api/pacientes/EXP001/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:48:32,321 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:48:32] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
[17/Aug/2025 15:48:32] "OPTIONS /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 0
WARNING 2025-08-17 15:48:32,334 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:48:32] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
[17/Aug/2025 15:48:57] "OPTIONS /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 0
WARNING 2025-08-17 15:48:57,075 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:48:57] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
[17/Aug/2025 15:48:57] "OPTIONS /api/pacientes/EXP001/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:48:57,892 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:48:57] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
[17/Aug/2025 15:49:16] "OPTIONS /api/pacientes/EXP001/historial/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:49:16,484 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:49:16] "GET /api/pacientes/EXP001/historial/ HTTP/1.1" 200 3803
WARNING 2025-08-17 15:50:36,455 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:50:36] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:50:36,461 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:50:36] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:53:59,555 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:53:59] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:53:59,567 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:53:59] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:54:04,975 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:04] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:54:16,616 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:16] "GET /api/pacientes/EXP001/historial/ HTTP/1.1" 200 3803
WARNING 2025-08-17 15:54:22,391 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:22] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:54:22,398 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:22] "GET /api/reports/dashboard/ HTTP/1.1" 200 515
WARNING 2025-08-17 15:54:24,937 middleware 49108 6161592320 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:54:24,938 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:24] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
[17/Aug/2025 15:54:24] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&sort_by=prioridad HTTP/1.1" 200 15200
[17/Aug/2025 15:54:26] "OPTIONS /api/recetas/101/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:54:26,440 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:26] "GET /api/recetas/101/ HTTP/1.1" 200 3049
WARNING 2025-08-17 15:54:31,237 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:31] "GET /api/recetas/101/ HTTP/1.1" 200 3049
[17/Aug/2025 15:54:39] "OPTIONS /api/recetas/101/detalles/295/lotes/list/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:54:39,453 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:39] "GET /api/recetas/101/detalles/295/lotes/list/ HTTP/1.1" 200 2
[17/Aug/2025 15:54:47] "OPTIONS /api/recetas/detalles/295/ HTTP/1.1" 200 0
WARNING 2025-08-17 15:54:47,368 middleware 49108 6161592320 No se pudo detectar usuario en middleware
Error al auditar cambios de PRESCRIPTION: 'Receta' object has no attribute 'id'
INFO 2025-08-17 15:54:47,380 middleware 49108 6161592320 Registro de auditoría creado: ACCESO por Usuario no identificado
[17/Aug/2025 15:54:47] "PATCH /api/recetas/detalles/295/ HTTP/1.1" 200 786
WARNING 2025-08-17 15:54:47,386 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:47] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:54:51,782 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:51] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:54:51,801 middleware 49108 6161592320 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:51] "GET /api/reports/dashboard/ HTTP/1.1" 200 515
WARNING 2025-08-17 15:54:53,819 middleware 49108 6161592320 No se pudo detectar usuario en middleware
WARNING 2025-08-17 15:54:53,820 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:54:53] "GET /api/audit/ HTTP/1.1" 200 5645
[17/Aug/2025 15:54:53] "GET /api/audit/stats/ HTTP/1.1" 200 885
WARNING 2025-08-17 15:55:24,936 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:24] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&sort_by=prioridad HTTP/1.1" 200 15200
WARNING 2025-08-17 15:55:25,591 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:25] "GET /api/recetas/estadisticas/ HTTP/1.1" 200 167
WARNING 2025-08-17 15:55:25,601 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:25] "GET /api/reports/dashboard/ HTTP/1.1" 200 515
WARNING 2025-08-17 15:55:29,858 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:29] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:55:30,227 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:30] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:55:31,450 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:31] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:55:33,343 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:33] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:55:33,352 middleware 49108 6178418688 No se pudo detectar usuario en middleware
[17/Aug/2025 15:55:33] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:37:51
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/base.py", line 556, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<function ManyToManyField.contribute_to_class.<locals>.resolve_through_model at 0x10b5789a0>: (models.E022) <function ManyToManyField.contribute_to_class.<locals>.resolve_through_model at 0x10b5789a0> contains a lazy reference to patients.pacientecie10, but app 'patients' doesn't provide model 'pacientecie10'.
patients.Paciente.cie10_codes: (fields.E331) Field specifies a many-to-many relation through model 'PacienteCIE10', which has not been installed.

System check identified 2 issues (0 silenced).
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/models.py changed, reloading.
Performing system checks...

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
WARNING 2025-08-17 15:57:24,938 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:57:24] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&sort_by=prioridad HTTP/1.1" 200 15200
WARNING 2025-08-17 15:58:24,936 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:58:24] "GET /api/recetas/cola-dispensacion-farmacia/?tipo=FARMACIA&estado=VALIDADA&sort_by=prioridad HTTP/1.1" 200 15200
WARNING 2025-08-17 15:59:09,686 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:09] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:59:09,692 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:09] "GET /api/auth/profile/ HTTP/1.1" 200 298
WARNING 2025-08-17 15:59:11,757 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:11] "GET /api/pacientes/buscar/?q=ecp001 HTTP/1.1" 200 24
WARNING 2025-08-17 15:59:12,138 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:12] "GET /api/pacientes/buscar/?q=ecp001 HTTP/1.1" 200 24
WARNING 2025-08-17 15:59:15,197 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:15] "GET /api/pacientes/buscar/?q=exp001 HTTP/1.1" 200 257
WARNING 2025-08-17 15:59:15,877 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:15] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:59:16,730 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:16] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
WARNING 2025-08-17 15:59:16,737 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:16] "GET /api/pacientes/cie10/buscar/?q=A82 HTTP/1.1" 200 1561
WARNING 2025-08-17 15:59:27,230 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:27] "GET /api/pacientes/EXP001/historial/ HTTP/1.1" 200 3803
WARNING 2025-08-17 15:59:37,768 middleware 49842 6130069504 No se pudo detectar usuario en middleware
[17/Aug/2025 15:59:37] "GET /api/pacientes/EXP001/ HTTP/1.1" 200 623
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 15:56:30
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/mau_hospital/urls.py", line 23, in <module>
    path('api/pacientes/', include('apps.patients.urls')),
                           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/urls.py", line 2, in <module>
    from . import views
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py", line 9, in <module>
    from .serializers import (
    ...<3 lines>...
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 161, in <module>
    class PacienteCIE10Serializer(serializers.ModelSerializer):
    ...<19 lines>...
            }
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 166, in PacienteCIE10Serializer
    class Meta:
    ...<4 lines>...
        ]
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 167, in Meta
    model = PacienteCIE10
            ^^^^^^^^^^^^^
NameError: name 'PacienteCIE10' is not defined
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 17, 2025 - 16:00:02
Django version 4.2.7, using settings 'mau_hospital.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/mau_hospital/urls.py", line 23, in <module>
    path('api/pacientes/', include('apps.patients.urls')),
                           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/urls.py", line 2, in <module>
    from . import views
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py", line 9, in <module>
    from .serializers import (
    ...<3 lines>...
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 4, in <module>
    class PacienteSerializer(serializers.ModelSerializer):
    ...<59 lines>...
            return value
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 9, in PacienteSerializer
    cie10_codes = PacienteCIE10Serializer(many=True, read_only=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'PacienteCIE10Serializer' is not defined
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/mau_hospital/urls.py", line 23, in <module>
    path('api/pacientes/', include('apps.patients.urls')),
                           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/urls.py", line 2, in <module>
    from . import views
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py", line 9, in <module>
    from .serializers import (
    ...<3 lines>...
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 4, in <module>
    class PacienteSerializer(serializers.ModelSerializer):
    ...<59 lines>...
            return value
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 9, in PacienteSerializer
    cie10_codes = PacienteCIE10Serializer(many=True, read_only=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'PacienteCIE10Serializer' is not defined
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
No se pudo registrar auditoría para Patient: App 'patients' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'prescriptions' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Patient: App 'inventory' doesn't have a 'Patient' model.
No se pudo registrar auditoría para Receta: App 'patients' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Receta: App 'inventory' doesn't have a 'Receta' model.
No se pudo registrar auditoría para Medicamento: App 'patients' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'prescriptions' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Medicamento: App 'inventory' doesn't have a 'Medicamento' model.
No se pudo registrar auditoría para Lote: App 'patients' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'prescriptions' doesn't have a 'Lote' model.
No se pudo registrar auditoría para Lote: App 'inventory' doesn't have a 'Lote' model.
No se pudo registrar auditoría para SystemMovement: App 'patients' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'prescriptions' doesn't have a 'SystemMovement' model.
No se pudo registrar auditoría para SystemMovement: App 'inventory' doesn't have a 'SystemMovement' model.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/mau_hospital/urls.py", line 23, in <module>
    path('api/pacientes/', include('apps.patients.urls')),
                           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/venv/lib/python3.13/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/urls.py", line 2, in <module>
    from . import views
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/views.py", line 9, in <module>
    from .serializers import (
    ...<3 lines>...
    )
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 4, in <module>
    class PacienteSerializer(serializers.ModelSerializer):
    ...<59 lines>...
            return value
  File "/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py", line 9, in PacienteSerializer
    cie10_codes = PacienteCIE10Serializer(many=True, read_only=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'PacienteCIE10Serializer' is not defined
/Users/jlrupton/DesarrolloLocal/MAU/backend/apps/patients/serializers.py changed, reloading.
Performing system checks...

Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [Errno 9] Bad file descriptor

Current thread 0x00000002072f45c0 (most recent call first):
  <no Python frame>
